title: Windtoday Blog
subtitle: windsurfing marketplace
description: windtoday is windsurfing marketplace to discover, compare & choose daily equipment offers. Pay and receive it at home, independently where you are.
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-archives
  - jekyll-autoprefixer
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

domain_name: http://blog.windtoday.com
google_analytics: UA-85604345-3
disqus: windtoday

# jekyll-paginate
paginate: 10
paginate_path: "/:num"
permalink: "/:title/"

# jekyll-seo
author:
  name: Windtoday Blog
  email: info@windtoday.co
  twitter: windtodayco

twitter:
  username: windtodayco

facebook:
  publisher: windtodayco

social:
  name: Windtoday
  links:
    - https://facebook.com/windtodayco
    - https://twitter.com/windtodayco

# jekyll-archive
jekyll-archives:
  enabled:
    - categories
  permalinks:
    category: /category/:name/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post

exclude:
  - package.json
  - node_modules
  - gulpfile.js
